# Generated by Django 5.0.7 on 2024-08-15 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '__first__'),
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goal.goal'),
        ),
    ]
