# Generated by Django 5.0.8 on 2024-08-15 11:15

import comic.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goal', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unlocked', models.BooleanField(default=False)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=comic.models.get_comic_image_path)),
                ('panel_number', models.IntegerField()),
                ('unlocked', models.BooleanField(default=False)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='comic.comic')),
            ],
        ),
    ]
