# Generated by Django 5.0.8 on 2024-08-15 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
        ('goal', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='goal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goal.goal'),
        ),
    ]
